initial commit
Madhusudan707/startup-reads pull request #1
Opened 2021-03-27 11:40 UTC by Xdev200

Name: Madhusudan Das
Project: https://startup-reads.netlify.app/

2021-03-29 07:06 UTC, Janaki2399 commented on src/components/Button/Button.jsx
> +const Button = ({text,btnClass,btnFunc,isDisabled}) => {
This is nice.You have passed the classes also as prop.I will try to use it this way too.

2021-03-29 07:06 UTC, Janaki2399 commented on src/components/Button/button.module.css
> +    display:grid;
Is there any specific reason for using grid for button class?

2021-03-29 07:06 UTC, Janaki2399 commented on src/components/Cart/Cart.jsx
> +            finalBill()
Calculating price should not be done in useEffect.useEffect is used only when you want to do things which are out of the scope for react. Like making network calls.The total price calculation can be normal function.

2021-03-29 07:06 UTC, Janaki2399 commented on src/contexts/contexts.js
> +    useEffect(()=>{
useEffect should not be used in the context .When you use a function or a state in the context it becomes  global to all its children.useEffect need not be global.The function that is used inside the useEffect can be global.This function can be called inside useEffect in the respective components.

2021-03-29 07:06 UTC, Janaki2399 commented on src/contexts/contexts.js
> +//2. CartContext
You can create seperate pages for different contexts.It would look more neat.

2021-03-29 07:06 UTC, Janaki2399 commented on src/components/Cart/Cart.jsx
> +        let newArr2=itemsInCart.filter((item)=>{
The function inside filter function should return only true or false.Each item in the array is passed to that function.If true is returned the item is retained else it is removed from array .
It can be implemented like this 
const newArray=itemsInCart.filter((item)=>item.isbn!==isbn)

2021-03-29 07:06 UTC, Janaki2399 commented on src/components/Card/Card.jsx
> +      if(item.isbn===product.isbn){
You can use ternary operator here.It would look neat.
Also this if loop looks very verbose.Try to create a function and call it inside .Also write a good function name which tells what is happening in the function

2021-03-29 07:06 UTC, Janaki2399 commented on src/components/Counter/Counter.jsx
> +                case '+':
You can use a flag value for increment/decrement instead of using symbols

2021-03-29 07:48 UTC, Xdev200 commented on src/components/Button/button.module.css
> +    display:grid;
I will remove this class because earlier I was using it, but now I am using button style from my component library CSS.

2021-03-30 17:38 UTC, purvasheth reviewed
Hi @Xdev200,

Your Ecommerce App looks amazing!
Loved it. Especially, the tabular display on the Cart page.
Kudos! on figuring out React Router yourself.
Few changes which will make it even better would be:
 
![image](https://user-images.githubusercontent.com/31120070/113031071-e1489e80-91ab-11eb-8967-227949c3fe71.png)
+ This can have a better styling -> space before radio button as well

![image](https://user-images.githubusercontent.com/31120070/113031145-f3c2d800-91ab-11eb-8166-87ad3675e6e8.png)
+ Good job on the hover styles. Add active style for what is selected at the moment as well.
Also, add the number of items in the cart and wishlist as a badge or simply as `CART(2)`
+ Remove from wishlist once added to cart and remove without adding to cart (This is an additional feature suggestion) 
+ Finally, add some feedback once the item is added to cart. Either make it `Go to Cart` or if you want to increment the quantity everytime user adds an item to cart, show a toast message.
+ Also don't forget to remove commented code :)

2021-03-30 17:38 UTC, purvasheth commented on src/App.test.js
> +import { render, screen } from '@testing-library/react';
Remove extra files like this if you aren't using them.
Will make it less intimidating for others to review your code if you have fewer files. :)

2021-03-30 17:38 UTC, purvasheth commented on src/components/Brand/Brand.jsx
> +       <>
You can directly return `<h1>` here. No need to add `<>...</>` here

2021-03-30 17:38 UTC, purvasheth commented on src/components/Button/Button.jsx
> +            <button style={{cursor:"pointer"}} className={btnClass} onClick={btnFunc} disabled={isDisabled}>{text}</button>
Avoid `style` attribute as much as possible. This  property can be added to button class in your component library or you can make a utility class in .css file like 
```
.clickable {
  cursor: pointer;
}
```
and use it like
```
 className={`clickable ${btnClass}`}
```

2021-03-30 17:38 UTC, purvasheth commented on src/components/Card/Card.jsx
> +import {useProducts,useCart,useWishList} from  '../../contexts/contexts'
Remove all commented code like this. Again something which makes the reviewer's life easy. :)

2021-03-30 17:38 UTC, purvasheth commented on src/components/Card/Card.jsx
> +          return (
since you are using an arrow function in map here, remove the `return` keyword. 
use the following syntax:
```
(product)=>(<div ............. )
```

2021-03-30 17:38 UTC, purvasheth commented on src/components/Card/Card.jsx
> +                <h4 style={{textAlign:"center",fontSize:"1rem",padding:"1rem"}}>{product.title}</h4>
Avoid inline styling as much as possible to make the code more readable.

2021-03-30 17:38 UTC, purvasheth commented on src/components/Cart/cart.module.css
> +and also iPads specifically.
Good idea to leave a comment like this. Will make your life easier when you get back to it after some time. :)

2021-03-30 17:38 UTC, purvasheth commented on src/components/Counter/Counter.jsx
> +                        setBtnDisable(true)
I know I am nitpicking with the next suggestion here. It's cool if you ignore it. :)
Your button has a hover style even after it is disabled, which can be removed.

2021-03-30 17:38 UTC, purvasheth commented on src/components/Form/Form.jsx
> +				<br/>
This seems very verbose. Think of using a loop here like following
```
Array.from(Array(6).keys()).map((index)=>(<input type='text' placeholder={`pt${index+1}`}/>))
```
It can be done in other ways too. Do whatever seems easy to you.

2021-03-30 17:38 UTC, purvasheth commented on src/components/Main/Main.jsx
> +            setProductList((productList)=>[...productList].sort((a, b) => parseFloat(a.price)-parseFloat(b.price)))
You are modifying the product list for sorting. It can be done just for rendering purposes.

2021-03-31 08:49 UTC, Xdev200 commented on src/components/Cart/Cart.jsx
> +        let newArr2=itemsInCart.filter((item)=>{
Done

2021-03-31 09:16 UTC, Xdev200 commented on src/components/Card/Card.jsx
> +          return (
I think here we can't omit the return key because there are multiple lines.

2021-03-31 09:39 UTC, purvasheth commented on src/components/Card/Card.jsx
> +          return (
We can still remove it. Keep the `()`

2021-04-05 18:27 UTC, kushanksriraj requested changes

2021-04-05 18:27 UTC, kushanksriraj commented on src/reducers/counter.js
> +      case 'increment':
Use all caps here: "INCREMENT"

2021-04-05 18:27 UTC, kushanksriraj commented on src/contexts/products.js
> +    <ProductsContext.Provider value={{ productsState:state, ProductsDispatch:dispatch }}>
Don't use capital for function names.

2021-04-05 18:27 UTC, kushanksriraj commented on src/reducers/products.js
> +        data: {},
Your data is initially an empty array. Don't assign an empty object here.

2021-04-05 18:27 UTC, kushanksriraj commented on src/reducers/wishlist.js
> +    error:''
Either use double quotes or single quotes. Keep it consistent.

2021-04-05 18:27 UTC, kushanksriraj commented on src/components/Main/Main.jsx
> +  const sortHandler = (sortStr) => {
Make a custom hook and separate the logic from the view.

2021-04-05 18:27 UTC, kushanksriraj commented on src/components/Card/Card.jsx
> +  /* 1 Wishlist Handler */
No comments needed here. The code is self explanatory.

2021-04-05 18:27 UTC, kushanksriraj commented on src/components/Card/Card.jsx
> +    let newArr = productsState.data.map((item) => {
Use const.

2021-04-05 18:27 UTC, kushanksriraj commented on src/components/Card/Card.jsx
> +              <img src={product.image} alt="product_img" loading="lazy" />
Nice. You are using lazy loading for the images.

2021-04-06 08:14 UTC, Xdev200 commented on src/components/Card/Card.jsx
> +              <img src={product.image} alt="product_img" loading="lazy" />
Thanks

2021-07-15 13:08 UTC, closed without merging